// Mocks generated by Mockito 5.0.10 from annotations
// in sfid_mobile/test/data/persistence/repository/post/post_repositort_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;
import 'dart:convert' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sfid_mobile/data/infrastructures/api_service_interface.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ApiServiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServiceInterface extends _i1.Mock
    implements _i2.ApiServiceInterface {
  MockApiServiceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> invokeHttp(dynamic url, _i2.RequestType? type,
          {Map<String, String>? headers,
          dynamic body,
          Map<String, String>? params,
          _i4.Encoding? encoding,
          bool? needThrowError}) =>
      (super.noSuchMethod(
          Invocation.method(#invokeHttp, [
            url,
            type
          ], {
            #headers: headers,
            #body: body,
            #params: params,
            #encoding: encoding,
            #needThrowError: needThrowError
          }),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
}
