// Mocks generated by Mockito 5.0.10 from annotations
// in sfid_mobile/test/use_cases/post/get_posts_use_case_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:soid_mobile/app/repositories/api/post_repository.dart' as _i2;
import 'package:soid_mobile/domains/post_domain.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [PostApiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostApiRepository extends _i1.Mock implements _i2.PostApiRepository {
  MockPostApiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Post>> getPosts() =>
      (super.noSuchMethod(Invocation.method(#getPosts, []),
              returnValue: Future<List<_i4.Post>>.value(<_i4.Post>[]))
          as _i3.Future<List<_i4.Post>>);
}
